# Generated by Django 5.1.4 on 2025-01-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
