# Generated by Django 5.1.5 on 2025-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_management', '0004_newspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
